# This is a basic workflow to help you get started with Actions

name: Deploy Aks
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} 
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }} 
  TF_RG_TFSTATE: ${{ secrets.TF_RG_TFSTATE }}
  TERRAGRUNT_CONFIG: ${{ secrets.TERRAGRUNT_CONFIG }} 
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  TF_VAR_OWNER: ${{ secrets.TF_VAR_OWNER }} 
  CI_PROJECT_NAME: ${{ secrets.CI_PROJECT_NAME }} 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  version:
    name: Example Terragrunt interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.29.6
      - name: show terragrunt version
        run: terragrunt --version
  plan:
    needs: [version]
    name: plan terragrunt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.29.6
      - name: plan terragrunt
        run: terragrunt run-all plan
      - name: apply terragrunt
        run: terragrunt run-all apply --terragrunt-non-interactive
      - name: destroy terragrunt
        run: terragrunt run-all destroy --terragrunt-non-interactive
      # Destroy if failure
      - name: Terraform Destroy
        run: terragrunt run-all destroy --terragrunt-non-interactive
        if: failure()